'use client'

import { useState } from 'react'
import { Wand2, Loader2, History, ChevronDown, ChevronUp, Copy, Check } from 'lucide-react'
import { formatDateTime } from '@/lib/utils'
import type { Script } from '@/types/database'

interface Props {
  leadId: string
  initialScripts: Script[]
}

type TabType = 'gatekeeper' | 'owner'

export default function ScriptsPanel({ leadId, initialScripts }: Props) {
  const [scripts, setScripts] = useState<Script[]>(initialScripts)
  const [activeTab, setActiveTab] = useState<TabType>('gatekeeper')
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showHistory, setShowHistory] = useState(false)
  const [copiedId, setCopiedId] = useState<string | null>(null)

  // Get latest version for each type
  const latestGatekeeper = scripts
    .filter(s => s.script_type === 'gatekeeper')
    .sort((a, b) => b.version - a.version)[0]

  const latestOwner = scripts
    .filter(s => s.script_type === 'owner')
    .sort((a, b) => b.version - a.version)[0]

  const currentScript = activeTab === 'gatekeeper' ? latestGatekeeper : latestOwner

  const handleGenerate = async () => {
    setGenerating(true)
    setError(null)

    try {
      const res = await fetch('/api/generate-scripts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ lead_id: leadId }),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || `HTTP ${res.status}`)
      }

      const data = await res.json()

      // Optimistically add new scripts to local state
      const now = new Date().toISOString()
      const nextVersion = data.version
      const model = data.model_used || 'gemini'

      const newScripts: Script[] = [
        {
          id: crypto.randomUUID(),
          lead_id: leadId,
          script_type: 'gatekeeper',
          content: data.gatekeeper_script,
          business_context_used: {},
          model_used: model,
          version: nextVersion,
          created_at: now,
        },
        {
          id: crypto.randomUUID(),
          lead_id: leadId,
          script_type: 'owner',
          content: data.owner_script,
          business_context_used: {},
          model_used: model,
          version: nextVersion,
          created_at: now,
        },
      ]

      setScripts(prev => [...prev, ...newScripts])
    } catch (err: any) {
      setError(err.message ?? 'Failed to generate scripts')
    } finally {
      setGenerating(false)
    }
  }

  const handleCopy = async (script: Script) => {
    try {
      await navigator.clipboard.writeText(script.content)
      setCopiedId(script.id)
      setTimeout(() => setCopiedId(null), 2000)
    } catch {}
  }

  const maxVersion = Math.max(0, ...scripts.map(s => s.version))
  const historyVersions = Array.from(
    new Set(scripts.map(s => s.version))
  ).sort((a, b) => b - a)

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem' }}>
        <div>
          <h3 style={{ margin: 0, fontSize: '0.95rem', fontWeight: '600' }}>AI Call Scripts</h3>
          {maxVersion > 0 && (
            <p style={{ margin: '2px 0 0', fontSize: '0.72rem', color: 'var(--foreground-muted)' }}>
              Version {maxVersion} · Generated by {currentScript?.model_used ?? 'AI'}
            </p>
          )}
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="btn btn-primary btn-sm"
          style={{ gap: '0.375rem' }}
        >
          {generating ? (
            <><Loader2 size={13} style={{ animation: 'spin 0.8s linear infinite' }} /> Generating...</>
          ) : (
            <><Wand2 size={13} /> {maxVersion === 0 ? 'Generate Scripts' : 'Regenerate'}</>
          )}
        </button>
      </div>

      {error && (
        <div style={{
          marginBottom: '0.875rem',
          padding: '0.625rem 0.75rem',
          background: 'rgba(239,68,68,0.1)',
          border: '1px solid rgba(239,68,68,0.3)',
          borderRadius: 'var(--radius)',
          color: '#f87171',
          fontSize: '0.8rem',
        }}>
          {error}
        </div>
      )}

      {maxVersion === 0 ? (
        /* Empty state */
        <div style={{
          textAlign: 'center',
          padding: '2.5rem 1.5rem',
          background: 'var(--surface-2)',
          borderRadius: 'var(--radius)',
          border: '1px dashed var(--border)',
        }}>
          <Wand2 size={28} style={{ opacity: 0.3, marginBottom: '0.75rem', color: 'var(--accent)' }} />
          <p style={{ fontWeight: '500', marginBottom: '0.25rem', color: 'var(--foreground)' }}>
            No scripts yet
          </p>
          <p style={{ fontSize: '0.8rem', color: 'var(--foreground-muted)', maxWidth: '280px', margin: '0 auto 1rem' }}>
            Click "Generate Scripts" to create personalized gatekeeper and owner scripts for this lead using AI.
          </p>
          <button onClick={handleGenerate} disabled={generating} className="btn btn-primary btn-sm">
            {generating ? <><Loader2 size={13} style={{ animation: 'spin 0.8s linear infinite' }} /> Generating...</> : <><Wand2 size={13} /> Generate Scripts</>}
          </button>
        </div>
      ) : (
        <>
          {/* Tabs */}
          <div className="tab-list">
            <button
              className={`tab ${activeTab === 'gatekeeper' ? 'active' : ''}`}
              onClick={() => setActiveTab('gatekeeper')}
            >
              🛡️ Gatekeeper Script
            </button>
            <button
              className={`tab ${activeTab === 'owner' ? 'active' : ''}`}
              onClick={() => setActiveTab('owner')}
            >
              🎯 Owner / Decision-Maker
            </button>
          </div>

          {/* Script Content */}
          {currentScript ? (
            <div style={{ position: 'relative' }}>
              <div className="script-content">
                {currentScript.content}
              </div>
              <button
                onClick={() => handleCopy(currentScript)}
                className="btn btn-secondary btn-sm"
                style={{ position: 'absolute', top: '0.625rem', right: '0.625rem', gap: '0.25rem' }}
                title="Copy to clipboard"
              >
                {copiedId === currentScript.id ? (
                  <><Check size={12} /> Copied!</>
                ) : (
                  <><Copy size={12} /> Copy</>
                )}
              </button>
            </div>
          ) : (
            <div style={{ padding: '1.5rem', textAlign: 'center', color: 'var(--foreground-muted)', fontSize: '0.875rem' }}>
              No script available for this tab.
            </div>
          )}

          {/* Version History */}
          {historyVersions.length > 1 && (
            <div style={{ marginTop: '0.875rem' }}>
              <button
                onClick={() => setShowHistory(h => !h)}
                className="btn btn-secondary btn-sm"
                style={{ gap: '0.375rem', fontSize: '0.75rem' }}
              >
                <History size={12} />
                Version history ({historyVersions.length})
                {showHistory ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
              </button>

              {showHistory && (
                <div style={{
                  marginTop: '0.625rem',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '0.375rem',
                }}>
                  {historyVersions.slice(1).map(version => {
                    const s = scripts.find(sc => sc.script_type === activeTab && sc.version === version)
                    if (!s) return null
                    return (
                      <div
                        key={version}
                        style={{
                          padding: '0.625rem 0.75rem',
                          background: 'var(--surface-2)',
                          border: '1px solid var(--border)',
                          borderRadius: 'var(--radius)',
                          fontSize: '0.78rem',
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.375rem' }}>
                          <span style={{ fontWeight: '500', color: 'var(--foreground-muted)' }}>Version {version}</span>
                          <span style={{ color: 'var(--foreground-subtle)' }}>{formatDateTime(s.created_at)}</span>
                        </div>
                        <p style={{ color: 'var(--foreground-muted)', margin: 0, lineHeight: '1.5' }}>
                          {s.content.slice(0, 120)}...
                        </p>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          )}
        </>
      )}
    </div>
  )
}
